// <auto-generated />
using System;
using Back_end;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Back_end.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 64)
                .HasAnnotation("ProductVersion", "5.0.4");

            modelBuilder.Entity("Back_end.Models.TipoIdentificacion", b =>
                {
                    b.Property<int>("IdTipoIdentificacion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("varchar(10)");

                    b.HasKey("IdTipoIdentificacion");

                    b.ToTable("TipoIdentificacion");
                });

            modelBuilder.Entity("Back_end.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("IdTipoIdentificacion")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("varchar(30)");

                    b.Property<int>("NumeroIdentificacion")
                        .HasColumnType("int");

                    b.Property<int?>("TipoIdentificacionIdTipoIdentificacion")
                        .HasColumnType("int");

                    b.HasKey("IdUsuario");

                    b.HasIndex("TipoIdentificacionIdTipoIdentificacion");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("Back_end.Models.Usuario", b =>
                {
                    b.HasOne("Back_end.Models.TipoIdentificacion", "TipoIdentificacion")
                        .WithMany()
                        .HasForeignKey("TipoIdentificacionIdTipoIdentificacion");

                    b.Navigation("TipoIdentificacion");
                });
#pragma warning restore 612, 618
        }
    }
}
